### ISSUE TITLE
Problem opencti synchronize 

### ISSUE THREAD

**Issue by G4fanhoto** [mkdemir/opencti-watcher#1]
Good morning friend, how are you, thanks for sharing the script, I'm trying to synchronize with my opencti and I have this problem below 

![Captura de tela 2023-05-28 094249](https://github.com/mkdemir/opencti-watcher/assets/122449332/d37e6b3a-7d2a-4d96-a1d2-4691d96f54c4)

Thanks

**Comment by mkdemir** [comment]
Hello Friend,

Thank you for reaching out to us and sharing the script. I understand that you are trying to sync with OpenCTI and are running into a problem. Based on the details provided, the solution appears to be in the .lenv copy and .env copy files located in the src folder. These files contain path information for log files and data files. Please follow the steps below to resolve the issue:

- Rename the **.lenv copy** file to **.lenv.**
- Try running the script again.

Best regards,
